---
#file: roles/common/tasks/main.yml

- name: Test Connection
  ping:

# Necessary for the frontend role "Sync API code" task.
# http://unix.stackexchange.com/questions/122616/why-do-i-need-a-tty-to-run-sudo-if-i-can-sudo-without-a-password
- name: Comment out `default requiretty` in /etc/sudoers
  sudo: yes
  replace: dest=/etc/sudoers regexp="^Defaults \s* requiretty" replace="# Defaults  requiretty"

- name: Run System Updates
  yum: name="*" state="latest"
  sudo: yes

- name: install git and wget
  yum: name={{item}} state="latest"
  sudo: yes
  with_items:
   - git
   - wget

- name: get epel package
  command: wget -r --no-parent -A 'epel-release-*.rpm' http://dl.fedoraproject.org/pub/epel/7/x86_64/e/
  sudo: yes

# TODO: Figure out better way to install this.
- name: install epel
  command: rpm -Uvh --replacepkgs dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-*.rpm
  sudo: yes
  ignore_errors: yes
